#undef TAPPING_TERM
#define TAPPING_TERM 175

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 900000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define AUTO_SHIFT_TIMEOUT 150
#define NO_AUTO_SHIFT_TAB
#define NO_AUTO_SHIFT_ALPHA
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "eVOpR/AzB9bo"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 7

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

